### ISSUE TITLE
Black Friday Discount for SaaS Pricer

### ISSUE THREAD

**Issue by tauslu** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#13]
Hello, 

Thank you for considering the deal. 

I created SaaS Pricer as a curation of SaaS pricing pages and their analysis on Airtable format. I normally sell them for 29 USD / year on Gumroad. There are now 202 product pricing on the listing. 

For Black Friday, I offer a 70% discount and the yearly subscription is 9 USD / year. 

The discount code is blackfriday21 and the gumroad link is https://saasprices.gumroad.com/l/saasprices

Thanks again

**Comment by twf-nikhila** [comment]
Added https://github.com/twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#books

Thank you
