### ISSUE TITLE
I have a JoinSecret 20% discount link if that helps. 

### ISSUE THREAD

**Issue by BernardPiette** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#24]
Not sure if you want affiliate links that give a discount. If so, please share the following. 
JoinSecret Founder Deals
20% Off all plans
https://www.joinsecret.com/?via=bernard
Hope that helps, if not, thanks for the collection either way. :-)
Bernard

**Comment by twf-nikhila** [comment]
@BernardPiette Sorry
