### ISSUE TITLE
Notion template and database

### ISSUE THREAD

**Issue by yihuiyihui** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#27]
| 1 | [Notion template to review and plan your week](https://yihuichan.gumroad.com/l/KfyIPC) | Reflect, focus, and plan your week with Notion (Comes with a blog post to explain how!) | 20% off using the code indiesale2021 | 22 Nov 2021 - 30 Nov 2021 |
| 2 | [Creator-maker starter pack](https://yihuichan.gumroad.com/l/gcgSP) | A curated list of resources and tools for new/aspiring creators and makers. (Comes with a blog post to explain more) | 20% off using the code indiesale2021 | 22 Nov 2021 - 30 Nov 2021 |

**Comment by twf-nikhila** [comment]
@yihuiyihui Added, Thanks for your contribution.
Please share it on your social media (Facebook, Twitter, LinkedIn, and any other places)

It helps all creators 💚
