### ISSUE TITLE
Mastering PhpStorm course Sale

### ISSUE THREAD

**Issue by christophrumpel** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#28]
Name: Mastering PhpStorm

Link: https://masteringphpstorm.com

Description: 
A video course for the state-of-the-art PHP developer who wants to work efficiently and successfully in a beautiful IDE.

Deal: -30%
Time: Only today 22nd of November

**Comment by twf-nikhila** [comment]
@christophrumpel added it.

You might consider extending it, this repository will be launched on PH on 23rd November.
