### ISSUE TITLE
Mission Control Plus and Batteries for Mac are 20% off for Black Friday using Code BLACKFRIDAY

### ISSUE THREAD

**Issue by ronyfadel** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#30]
Mission Control Plus: https://fadel.io/missioncontrolplus
Batteries for Mac: https://fadel.io/batteries

**Comment by twf-nikhila** [comment]
@ronyfadel Added them, Thank you

You can add more which you find interesting & is missing here, it will help others 💚
