### ISSUE TITLE
Please Add Nessus Professional 50% Off

### ISSUE THREAD

**Issue by tenK2020** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#32]
**50% Off Nessus Professional** (https://store.tenable.com/1479/purl-webNessusOneYearOptin?x-promotion=GBF) Offer valid Wednesday through Monday - Use Code "TakeHalf"

**Comment by twf-nikhila** [comment]
@tenK2020 Thank you, added it.!
