### ISSUE TITLE
Laravel Security in Depth - lifetime 25% off

### ISSUE THREAD

**Issue by valorin** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#35]
I'm not entirely sure where it fits in your categories, but can you please add:

Name: Laravel Security in Depth

Link: https://larasec.substack.com/blackfriday2021

Description:
Monthly newsletter that covers Laravel Security topics in Depth, with interactive demos where you can safely explore known vulnerabilities.

Deal: 25% off, forever

Time: Until the end of November

**Comment by twf-nikhila** [comment]
@valorin added to courses! Thank you
