### ISSUE TITLE
No Code MBA

### ISSUE THREAD

**Issue by sethkramer1** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#40]
No Code MBA (nocode.mba) will be 50% off on Black Friday - discount will be automatically applied without a code.

**Comment by twf-nikhila** [comment]
@sethkramer1 Added in the course section
https://github.com/twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals/blob/main/README.md#courses
