### ISSUE TITLE
ShiftApp Employee Scheduling  - Black Friday Deal 2022

### ISSUE THREAD

**Issue by jlsync** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#56]
Our SaaS software , ShiftApp https://shiftapp.com/ has a BF/CM deal in 2022, 77% off for 7 months on all plans. Deal page is at https://shiftapp.com/black-friday until November 30th 2022.

|# | Name | Description | Deal details (Discount & coupon code) | Start-End date
|-- | -- | -- | -- | --
|1 | [ShiftApp](https://shiftapp.com/) | Easy-to-use Employee Scheduling and Shift Planning Software. | 77% off for 7 months on all Plans. [Visit Deal Page](https://shiftapp.com/black-friday) | now to 30-Nov-2021 (Black Friday/Cyber Monday)

**Comment by twf-nikhila** [comment]
@jlsync Added!

**Please do star⭐ this repository & share the link on social media.**
