### ISSUE TITLE
Security For Everyone - Black Friday Deal 2022

### ISSUE THREAD

**Issue by hczdmr** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#69]
| **#** | **Name** | **Description**| **Deal details** (Discount & coupon code)| **Start-End date** |
|:-:|:-:|:-:|:-:|:-:
| 1 | [SecurityForEveryone](https://securityforeveryone.com/products/continuous-security?utm_source=github&utm_medium=readme&utm_campaign=blackfriday) | Security For Everyone - Continuous Security Scanner & Unlimited Manual Scan  |  50% off with code: BLACKFRIDAY [Visit Deal Page](https://securityforeveryone.com/blog/black-friday-discount-and-2022-statistics) | now to 30th November |

**Comment by twf-nikhila** [comment]
@hczdmr Added!

**Please do star⭐ this repository & share the link on social media.**
