### ISSUE TITLE
BusKill 10% off

### ISSUE THREAD

**Issue by maltfield** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#70]
Please add the 10% off Black Friday deal for BusKill

#### The Deal

BusKill's black friday deal is 10% off all products purchased between Nov 19 to Dec 04 2022.

No code is needed. The total will be reduced by 10% at checkout for all orders paid with cryptocurrencies.

 * https://www.buskill.in/bitcoin-black-friday-2022/

#### What is BusKill?

BusKill is an open-source hardware and software project that uses a hardware tripwire/dead-man-switch (a usb cable with a magnetic breakaway) to trigger your computer to lock or shutdown if the user is physically separated from their machine.

 * https://en.wikipedia.org/wiki/BusKill

The following guide describes how BusKill can be configured to wipe the LUKS Header (containing the FDE key) and its metadata. It shows a video demo where the machine wiped the keys & powered-off in <6 seconds, and it includes a post-execution forensic analysis in Kali with bulk_extractor

 * https://www.buskill.in/luks-self-destruct/

**Comment by twf-nikhila** [comment]
@maltfield Added!

**Please do star⭐ this repository & share the link on social media.**
