### ISSUE TITLE
Please add my BFCM deal

### ISSUE THREAD

**Issue by ayushgit** [twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#9]
Category - Books

1.
Name - 7 Habits of highly effective Tweeple - The Wisdom of Twitter
Description - The definitive guide to using Twitter as an indie creator, maker, networker, and even consumer. 136 pages of actionable content that you can start applying from day 1. 
Deal details - code "bfcm" for 50% off the retail price.
Start-end date - Started - Ends December 1st.
Link - https://thewisdomproject.gumroad.com/l/sTFzn
2
Name - The Toolkit for Atomic Habits
Description - The complete guide to deploying the wisdom of the book Atomic Habits in your day-to-day life. 48 Page beautifully designed and illustrated printable PDF + Notion template + Google Sheet template. Complete behavior change system.
Deal details - code "bfcm" for 50% off the retail price.
Start-end date - Started - Ends December 1st.
Link - https://thewisdomproject.gumroad.com/l/habit_toolkit
3.
Name - The Wisdom of Atomic Habits
Description - The most actionable summary of the book Atomic Habits. Get the best insights to build life-changing habits in 30 minutes instead of 4 hours. Most wisdom per word of any info product.
Deal details - code "bfcm" for 50% off the retail price.
Start-end date - Started - Ends December 1st.
https://thewisdomproject.gumroad.com/l/wisdom_atomic_habits

My Twitter handle for any questions - [@ayushtweetshere](https://twitter.com/ayushtweetshere)

**Comment by twf-nikhila** [comment]
@ayushgit Added.

Check here: https://github.com/twf-nikhila/Awesome-Black-Friday-Cyber-Monday-deals#books
